#!/usr/bin/env bash

# Copies the build cache from a special dir into a place where the build system can
# use it. Copying like this ensures that the build cache is present in the
# final image, which is necessary for packages containing messages.

set -o errexit
set -o pipefail
set -o nounset

# This directory is mounted by the Dockerfile and is unique to each project.
BUILD_CACHE=/colcon-build-cache/testing_um_template/

if [[ ! -d "${BUILD_CACHE}" ]]; then
  echo "Build cache directory not mounted" >&2
  exit 1
fi

rm -rf /robot/build
cp -r ${BUILD_CACHE} /robot/build
